image: docker:20.10.11-alpine3.14

services:
  - docker:20.10.11-dind-alpine3.14
    command: [ "--tls=false" ]

variables:
  APP_VERSION: 1.0.0
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

build:
  stage: build
  only:
    - master
    - /^v[0-9\.]$/
    - dev
    - /^dev_[0-9\.]$/
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$APP_VERSION --tag $CI_REGISTRY_IMAGE:latest .
    - docker push --all-tags $CI_REGISTRY_IMAGE

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml